### ISSUE TITLE
Microsoft.FeatureManagment package

### ISSUE THREAD

**Issue by amafernandes** [microsoft/featurebits#55]
There is any relation with the development of the package Microsoft.FeatureManagement, [nuget](https://www.nuget.org/packages/Microsoft.FeatureManagement), [github](https://github.com/microsoft/FeatureManagement-Dotnet), [documentation](https://docs.microsoft.com/en-us/dotnet/api/microsoft.featuremanagement?view=azure-dotnet-preview), that seems to come from the Azure team.
Both packages have related goals, they work both on netcore.
It would be better, IMHO, tohave a unified approach to feature flags.

**Comment by dseelinger** [comment]
FeatureBits has no direct relation to https://github.com/microsoft/FeatureManagement-Dotnet, which is part of the Microsoft Azure App Configuration service. That App Configuration service (currently in preview) is Microsoft's official way to manage Azure App Configuration, including Feature Flags/Feature Toggles.

On the other hand, FeatureBits is a standalone feature-flagging library and is not dependent on any Azure services. It is used by a small team at Microsoft and existed before Azure App Config or FeatureMagement-dotnet were available. Because at the time we saw no other free options for feature-flagging that fit our needs, we developed our own library and open-sourced it. 

We have talked with the Azure App Configuration team and together decided to keep the two repos separate, though even our own team may switch to Azure App Configuration in the future when it becomes available in the environments we work with.

Sorry for any confusion. If in doubt, go with [Azure App Configuration](https://azure.microsoft.com/en-us/services/app-configuration/).
